# @url = http://localhost:3000/auth/graphql
# @url = http://jobber-local.com/auth/graphql
# @ host = jobber-local.com
# @url = http://k8s-myingressgroup-9cf944356d-2123168966.eu-north-1.elb.amazonaws.com/auth/graphql

# @host = jobber-backend.com

@url = https://jobber.peelmicro.info/auth/graphql

# @host = jobber.peelmicro.info
### Login
# @name login
POST {{url}}
# Host: {{host}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  login(loginInput: {
    email: "my-email2@msn.com",
    password: "MyPassword1!"
  }) {
    id
  }
}

### Install httpbin and run using docker with "docker run -p 80:80 kennethreitz/httpbin"

GET http://0.0.0.0:80/anything
Content-Type: application/json
X-Full-Response: {{login.response.body.*}}

### Get all users
POST {{url}}
# Host: {{host}}
Content-Type: application/json
Cookie: {{login.response.headers.Set-Cookie}}
X-REQUEST-TYPE: GraphQL

query {
  users
  {
    id
    email
    createdAt
    updatedAt
  }
}

### Get a user by email

POST {{url}}
# Host: {{host}}
Content-Type: application/json
Cookie: {{login.response.headers.Set-Cookie}}
X-REQUEST-TYPE: GraphQL

query {
  userByEmail(email: "my-email2@msn.com")
  {
    id
    email
    createdAt
    updatedAt
  }
}

### Get a user by id

POST {{url}}
# Host: {{host}}
Content-Type: application/json
Cookie: {{login.response.headers.Set-Cookie}}
X-REQUEST-TYPE: GraphQL

query {
  user(id: 1)
  {
    id
    email
    createdAt
    updatedAt
  }
}

### Get a user from the cookie

POST {{url}}
# Host: {{host}}
Content-Type: application/json
Cookie: {{login.response.headers.Set-Cookie}}
X-REQUEST-TYPE: GraphQL

query {
  getUserFromCookie
  {
    id
    email
    createdAt
    updatedAt
  }
}

### Create a user

POST {{url}}
# Host: {{host}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  upsertUser(upsertUserInput: {
    email: "my-email3@msn.com",
    password: "MyPassword3!"
  })
  {
    id
    email
    createdAt
    updatedAt
  }
}

### Update password for a user

POST {{url}}
# Host: {{host}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  upsertUser(upsertUserInput: {
    email: "my-email2@msn.com",
    password: "MyPassword1!",
    newPassword: "MyPassword2!"
  })
  {
    id
    email
    createdAt
    updatedAt
  }
}
