services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_MULTIPLE_DATABASES: auth
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
