@url = http://localhost:3000

### Login with GraphQL
POST {{url}}/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  login(loginInput: { email: "my-email2@msn.com", password: "MyPassword2!" }) {
    id
  }
}
