name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - run: npm ci --legacy-peer-deps

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      # - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # - run: npm install -g npm-check-updates
      # - run: ncu -u
      - run: npm ci --legacy-peer-deps

      # This could be not needed, because we are not going to use Nx Cloud
      # - uses: nrwl/nx-set-shas@v4
      #   with:
      #     main-branch-name: main
      #     set-environment-variables-for-job: true
      #     error-on-no-successful-workflow: false

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: npx nx-cloud record -- echo Hello World
      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
      # - run: npx nx affected -t lint test build # This is not needed, because we are not using Nx Cloud
      - run: npx nx run-many -t lint test build --all # Run on ALL projects, this is a better approach than nx affected if we don't use Nx Cloud
        env:
          NX_VERBOSE_LOGGING: 'true'
